# Generated by Django 4.2.23 on 2025-08-28 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0001_initial'),
        ('quotes', '0002_quoterequest_details_alter_quoterequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='premium_amount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='status',
        ),
        migrations.AddField(
            model_name='quote',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='response_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='quote',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='insurers.insurer'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='insurers.insuranceplan'),
        ),
    ]
