version: "3.8"
services:
  db:
    image: postgres:15
    env_file: ./backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: ./backend
    command: bash -c "python manage.py migrate && gunicorn insureconnect.wsgi:application --bind 0.0.0.0:8000"
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: ./backend
    command: celery -A insureconnect worker --loglevel=info
    env_file: ./backend/.env
    depends_on:
      - db
      - redis

  beat:
    build: ./backend
    command: celery -A insureconnect beat --loglevel=info
    env_file: ./backend/.env
    depends_on:
      - db
      - redis

volumes:
  pgdata:
